library(TwoSampleMR)
library(pleio)
library(readxl)
library(dplyr)
library(ieugwasr)
Sys.setenv(OPENGWAS_JWT="")
ROMO1 <- extract_instruments(
  outcomes = "eqtl-a-ENSG00000125995", 
  p1 = 5e-06, 
  clump = TRUE, 
  r2 = 0.001,
  kb=100)
outcome_dat1 <- extract_outcome_data(snps = ROMO1$SNP, outcomes = 'finn-b-RHEUMA_SEROPOS_OTH')
dat1 <- harmonise_data(exposure_dat = ROMO1, outcome_dat = outcome_dat1)
res1 <- mr(dat1)
OR1 <- generate_odds_ratios(res1)
het1 <- mr_heterogeneity(dat1)
pleio1 <- mr_pleiotropy_test(dat1)
dat1$F_stat <- (dat1$beta.exposure / dat1$se.exposure)^2
res_loo1 <- mr_leaveoneout(dat1)
p_loo1 <- mr_leaveoneout_plot(res_loo1)
p_scatter1 <- mr_scatter_plot(res1, dat1)
res_single1 <- mr_singlesnp(dat1)
p_funnel1 <- mr_funnel_plot(res_single1)
p_forest1 <- mr_forest_plot(res_single1)
write.csv(OR1, "Table_ROMO1_to_RA_MR_Results.csv", row.names = FALSE)
write.csv(het1, "Table_ROMO1_to_RA_Heterogeneity.csv", row.names = FALSE)
write.csv(pleio1, "Table_ROMO1_to_RA_Pleiotropy.csv", row.names = FALSE)
write.csv(data.frame(SNP=dat1$SNP, F_statistic=dat1$F_stat), "Table_ROMO1_to_RA_F_stats.csv", row.names = FALSE)
pdf("Plot_ROMO1_to_RA_Sensitivity.pdf", width = 10, height = 8)
print(p_loo1)
dev.off()
outcome_dat2 <- extract_outcome_data(snps = ROMO1$SNP, outcomes = 'ebi-a-GCST90001935')
dat2 <- harmonise_data(exposure_dat = ROMO1, outcome_dat = outcome_dat2)
res2 <- mr(dat2)
OR2 <- generate_odds_ratios(res2)
het2 <- mr_heterogeneity(dat2)
pleio2 <- mr_pleiotropy_test(dat2)
dat2$F_stat <- (dat2$beta.exposure / dat2$se.exposure)^2
res_loo2 <- mr_leaveoneout(dat2)
p_loo2 <- mr_leaveoneout_plot(res_loo2)
p_scatter2 <- mr_scatter_plot(res2, dat2)
res_single2 <- mr_singlesnp(dat2)
p_funnel2 <- mr_funnel_plot(res_single2)
p_forest2 <- mr_forest_plot(res_single2)
write.csv(OR2, "Table_ROMO1_to_IL2RA_MR_Results.csv", row.names = FALSE)
write.csv(het2, "Table_ROMO1_to_IL2RA_Heterogeneity.csv", row.names = FALSE)
write.csv(pleio2, "Table_ROMO1_to_IL2RA_Pleiotropy.csv", row.names = FALSE)
write.csv(data.frame(SNP=dat2$SNP, F_statistic=dat2$F_stat), "Table_ROMO1_to_IL2RA_F_stats.csv", row.names = FALSE)
pdf("Plot_ROMO1_to_IL2RA_Sensitivity.pdf", width = 10, height = 8)
print(p_loo2)
dev.off()
outcome_dat3 <- extract_outcome_data(snps = ROMO1$SNP, outcomes = 'ebi-a-GCST90001988')
dat3 <- harmonise_data(exposure_dat = ROMO1, outcome_dat = outcome_dat3)
res3 <- mr(dat3)
OR3 <- generate_odds_ratios(res3)
het3 <- mr_heterogeneity(dat3)
pleio3 <- mr_pleiotropy_test(dat3)
dat3$F_stat <- (dat3$beta.exposure / dat3$se.exposure)^2
res_loo3 <- mr_leaveoneout(dat3)
p_loo3 <- mr_leaveoneout_plot(res_loo3)
p_scatter3 <- mr_scatter_plot(res3, dat3)
res_single3 <- mr_singlesnp(dat3)
p_funnel3 <- mr_funnel_plot(res_single3)
p_forest3 <- mr_forest_plot(res_single3)
write.csv(OR3, "Table_ROMO1_to_HLADR_MR_Results.csv", row.names = FALSE)
write.csv(het3, "Table_ROMO1_to_HLADR_Heterogeneity.csv", row.names = FALSE)
write.csv(pleio3, "Table_ROMO1_to_HLADR_Pleiotropy.csv", row.names = FALSE)
write.csv(data.frame(SNP=dat3$SNP, F_statistic=dat3$F_stat), "Table_ROMO1_to_HLADR_F_stats.csv", row.names = FALSE)
pdf("Plot_ROMO1_to_HLADR_Sensitivity.pdf", width = 10, height = 8)
print(p_loo3)
dev.off()
